### ISSUE TITLE
PSR-6: List of implementation problems

### ISSUE THREAD

**Issue by milesj** [php-fig/fig-standards#389] opened 2014-12-04 19:27 UTC
I decided to update one of my codebases in preparation for PSR-6 by copying the current proposal and modifying my code accordingly. The code can be found here: https://github.com/titon/framework/tree/master/src/Titon/Cache (Do note that the project is in Hack and that the Storage class is the pool).

While implementing the code, I found some weird implementations that don't make much sense, so I thought I would point them all out in a giant ticket.

## Item::exists() should be removed ##

This method should return a true or false if the item exists. An item is either a hit (it exists), or a miss (it doesn't exist), so why do we have a method to check it again? To see if it expired in that short timeframe? I can't seem to find a use case.

Honestly, the pool should handle this as the pool is the abstract layer and supports multiple implementations (memcache, redis, filesystem, etc). The item has no concept of the pools implementation, so can not successfully check if the item exists as it doesn't know which engine it is communicating with (memcache, etc).

I could find no way to successfully implement this without passing the pool into the item, which I do not want to do. For now, I'm just throwing an exception if you call the method. https://github.com/titon/framework/blob/master/src/Titon/Cache/Item.hh#L66

## Item::get() should not return null for misses ##

According to the docblocks of this method "if isHit() returns false, this method MUST return null.". The problem with this statement is that you can no longer set a value on a missed item and re-save it. Take the following example from the meta docs:

```pph
function get_widget_list()
{
    $pool = get_cache_pool('widgets');
    $item = $pool->getItem('widget_list');
    if (!$item->isHit()) {
        $value = compute_expensive_widget_list();
        $item->set($value);
        $pool->save($item);
    }
    return $item->get();
}
```

The `$pool->save($item);` line would fail as `$item->get()` would always return `null` and would not represent the new `$value` (the return statement would also return `null` instead of `$value`). If our `Item` implementation changes `isHit()` to be true when we set a new value, the state of this item is no longer a true representation.

I believe the solution is to have `get()` return whatever the default item value is, usually null. This is acceptable since a missed item wouldn't have a value anyways.

## Item::getExpiration() returning the expires for missed items ## 

According to the docblocks of this method "If this cache item is a Cache Miss, this method MAY return the time at which the item expired or the current time if that is not available.". Missed item's don't have expiration times as they no longer exist, or am I wrong on this? I have yet to see/find a way to implement this, so any guidance would be helpful.

I believe this method should return null for misses/hits and should only return a value when something is going to be saved.

## Can't re-save a hit item without an expiration date ##

If you retrieve an item, and it is a hit, you can't re-save the item without setting an expiration date as the expiration is not returned from the cache engine. Perhaps we should throw an exception if you try to save without setting the expiration date.

## Missing methods ##

I agree with the method additions/changes from this pull request #361

**Comment by matthiasmullie** [comment] 2015-02-17 13:02
# What's the point of Item::getExpiration()

Some cache backends make it (nearly) impossible to get the expiration date of a value in cache, e.g. memcache.

I guess this method exists not for implementing libraries to request expiration date of a value, but for CacheItemPoolInterface to be able to get the expiration date when it’s about to save() a new value? In that case, I’d prefer to omit it from the interface, and let whoever builds CacheItemInterface implementations figure out how to transfer expiration date to CacheItemPoolInterface.

If it is meant to be exposed to implementing libraries: what’s the use for wanting to know when an object expires? For cache backends that don’t allow a(n easy) way to get a value’s expiration time, the only way to implement this is to also save it, thus filling up your cache with potentially useless data, just because the interface mandates it could be requested.

I would rather see this method removed (or at least better understand the rationale behind it)

# Why make Item::getExpiration() return DateTime

CacheItemInterface::getExpiration is supposed to return a \DateTime object. What’s proposed for permanent cache values?
* Also allow it to return null for such cases?
* Extend DateTime, making a InifinityDateTime or similar? (bah! but the only way to do it & match current spec...)
* anything obvious I missed?

# save() & saveDeferred() interaction

I assume a save() doesn’t automatically commit a bunch of not-yet-committed saveDeferred() items - it probably only saves the 1 particular item?

If yes: what if save() saves a duplicate of a key that is already in non-committed saveDeferred? Does it cancel out the deferred key, making sure it’s not going to be committed later, or can the commit still overwrite that key, even though it was added earlier?

I assume save() doesn't commit or cancel out not-yet-committed deferred items & the deferred item will just overwrite the save()'d one once it's committed? I just want to make sure ;)

**Comment by sagikazarmark** [comment] 2015-07-15 16:53
# Item::get() should not return null for misses

Making cache items immutable would solve this problem, as the new item would become a hit.

**Comment by aequasi** [comment] 2015-12-03 09:03
Should Item::expiresAt have a typehint for `\DateTimeInterface`?

**Comment by oxman** [comment] 2015-12-14 15:11
```new CacheItem``` sould be allowed.
Because there is some case when you want write in cache system and you don't care if the data is already in cache or not.
If you don't allow ```new CacheItem``` you force system to do a hit on cache system.

**Comment by Chippiewill** [comment] 2015-12-14 15:18
`new CacheItem` does not fit the 90% use-case. Typically if you are using it as a Cache you only want to update something if it's expired.

Regardless the issue is rather closed at this point and you should direct any concerns to the mailing list.

**Comment by michaelcullum** [comment] 2016-02-15 14:04
PSR-6 is final and won't change now. You're welcome to discuss this further on the ML for future PSRs.

**Closed by michaelcullum** 2016-02-15 14:04 UTC
