### ISSUE TITLE
[PSR-7] "HTTP Message Meta Document": Please add a layman's introduction

### ISSUE THREAD

**Issue by donquixote** [php-fig/fig-standards#355] opened 2014-10-15 21:11 UTC
[Currently](https://github.com/php-fig/fig-standards/blob/06da7429243e7e9231c0882d6a43fd321b0affe7/proposed/http-message-meta.md), the "HTTP Message Meta Document" has a very very short intro, and then it jumps straight to the details. Everyone reading this for the first time will be "what?". It is a bit like tuning into a presentation 10 minutes after it has started.

And before any explanation of MessageInterface, we can read
> The design of the MessageInterface, RequestInterface, IncomingRequestInterface, and ResponseInterface interfaces are based on [..]

Duh.

### Solution
Write an introduction to explain the context of this proposal:
* What are HTTP messages? This does not need to be a detailed explanation, but the RFC link is clearly not enough. Noone likes to read RFC documents.
* What does PHP want to do with them?
  (send and receive and work with them them, I suppose)
  Maybe people already know more or less what a HTTP message is, but not exactly what this would mean in a PHP context. E.g. is the Symfony "Request" object a HTTP message?
* Are there existing implementations? What are they doing right? What are the problems?
* What does this PSR plan to do?
  What is the initial idea of the initiators of the PSR? What are the points that still need to be discussed?
  How will people use the PSR?

Example:

> The idea is to publish a library with common interfaces for objects that represent HTTP messages. The library will be published and maintained by the PHP-FIG group, and can be added as a dependency to other packages. Currently the following interfaces are planned: MessageInterface, RequestInterface, IncomingRequestInterface, ResponseInterface.

Maybe some of this could go into a separate document / page / blog post.

**Comment by weierophinney** [comment] 2015-01-04 13:29
@dragoonis Can you close this, please? I've had no feedback from the reporter on the updates I've done, so I'll assume that the issue is addressed.

**Closed** 2015-01-29 15:13 UTC
