### ISSUE TITLE
[PSR-0] deprecation

### ISSUE THREAD

**Issue by jslegers** [php-fig/fig-standards#448] opened 2015-03-03 12:50 UTC
Why has PSR-0 been deprecated?

IMO, PSR-0 remains the more elegant approach, compared with PSR-4. Also, the lack of compatibility between PSR-0 and PSR-4 adds needless complexity to applications.

I really don't get why anyone would decide to deprecate PSR-0. Why can't it co-exist with PSR-4 as an alternative standard?

**Comment by jslegers** [comment] 2015-03-03 13:18
I love PSR-0! The ability to use the `_` in class names as an equivalent to directory separators in paths, PSR-0 allows you to create multiple libraries for the same namespace that can reference each other without having to use those nasty `use ...` statements or having to reference the full namespace.

By removing the special meaning of the `_`  character, PSR-4 both removes that very useful ability forces us to support two different standards if we still want to use older libraries in our projects. That adds needless complexity and loading time to zero-config autoloaders.

I've always considered PSR-4 a very bad standard, but deprecation of PSR-0 is even worse, as it literally FORCES me to wrote needlessly convoluted code.

See also https://github.com/php-fig/fig-standards/pull/341.

**Comment by philsturgeon** [comment] 2015-03-03 13:23
Duplicate of comments left on #341.

**Closed** 2015-03-03 13:23 UTC

**Comment by jslegers** [comment] 2015-03-03 13:27
@philsturgeon :

Why on earth was this decision made?

I really see no only downsides to either using PSR-4 or deprecating PSR-0.

I find decisions like these nearly cringeworthy enough to change professions...

**Comment by philsturgeon** [comment] 2015-03-03 13:29
So when I closed this as a duplicate I wasn't expecting you to start chatting on the 2nd thread again. Pick one thread and we can talk there.

https://github.com/php-fig/fig-standards/pull/341#issuecomment-76944287

**Comment by jslegers** [comment] 2015-03-03 13:42
@philsturgeon :

Someone closed access for me at https://github.com/php-fig/fig-standards/pull/341.
That feels like censorship to me.

Anyway, herebelow are my comments to what you said there.

> Because having two standards doing the same thing is moronic.

IMO it was ironic to drop the translation of the  `_` symbol to directory separators in PSR-4. This, both because it breaks compatibility with PSR-0 (*) and because it forces you to use the full namespace for any library, even when that library belongs to the same package (**).

> It also sounds like your problem is more with actual namespaces than PSR-4.

Namespaces are a great way to prevent conflicts between different packages. 

It makes no sense whatsoever to use different namespaces for different libraries that belong to the same package. It either (1) makes code needlessly convoluted be requiring one to use the full namespace for every reference to a class or (2) requiring the use of the `use` statement, which is really no better than adding a `require` or `require_one` statement on top the way we used to.

> If you're not a fan of use statements then at least they get a little easier in PHP 7.

As I said, `use` statements are really no better than adding a `require` or `require_one` statement on top.

> Either way, PSR-0 was old and broken and you should be happy with PSR-4 as namespaces are how this stuff is meant to work

With PRS-0, I was able to use namespaces for what they're intended : avoiding naming conflicts between packages, while keeping naming conventions within the same package clean and simple.

With PRS-0, I could just use a simple [autoloader](https://github.com/PHPPowertools/Loader) that can load any of those +15,000 PSR-0 compatible libraries out of the box without ANY need for additional configuration.

PSR-4 needlessly removes those possibilities while adding nothing of value.

*) which requires autoloaders to be needlessly complex
**) which makes writing libraries that belong to the same package needlessly complex

**Comment by philsturgeon** [comment] 2015-03-03 14:51
I closed it down because this is an old irrelevant conversation and we're having it on Twitter anyway now.

I don't think we had the ability to lock when this vote was held. I'd have locked it then if I did. 

You seem to have an non-standard view on how namespaces are used. You want to pretend that PHP has a package system, and use namespaces only for the vendor and keep everything else in a _.

That is not how any of the FIG does things these days, and as such the standard does not reflect that.

You should keep using PSR-0 for as long as you feel comfortable using it. Deprecated does not mean gone, it just means people should probably start using the newer one.

I've read that blogpost about how he said we should not deprecate PSR-0, but then we had a little chat and he came around:

> Update
> I had a conversation with Phil on Twitter and there are a couple of things to clarify.

> First, pushing back on PSR-0 deprecation isn’t about forcing people to use the same folder structure, but about preserving the viability of the implicit foldier hierarchy guidelines in PSR-0. My concern was that by deprecating PSR-0, it would signal that the hierarchy guidelines were to be avoided even though PSR-4 only provided a replacement for PSR-0’s autoloader specification and was silent on organization.

> Second, Phil assured that by deprecation, it would simply mean that PSR-4 would be recommended over PSR-0, and it’s not disavowal of PSR-0: everything still using PSR-0 should continue to be able to do so “forever”.

> In effect, it would be to deprecate PSR-0’s autoloader in favor of PSR-4, but say nothing about the folder hierarchy guidelines. If you want to structure your library to be PSR-0 compliant (in addition to being PSR-4 compliant), the PHP-FIG would not be saying that you’re doing it wrong. That’s something I can agree with.

There were a few folks on the FIG against deprecation too, but that's why there are votes, and the vote is decided, so this conversation is wildly moot.

You mentioned on Twitter writing a blog post about it, Feel free to do that instead of necrobumping old pull requests and starting new issues.
